# Site settings
title: Anh Le
email: anh.le91@gmail.com
description: "This is my personal web page. Included is my work and blog posts"
baseurl: ""
url: "http://ladilettante.github.io"
twitter_username: anh_q_le
github_username:  LaDilettante
# facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]

# Collection setting for statbook
collections: 
  statbook:
    output: true

render: statbook
